### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by trfiladelfo** [danielkaiser/python-chromedriver-binary#17]
Hi,

I'm trying to install lib to install pip... but in Chromedriver download there was an SSL certificate error.

`  Running setup.py install for chromedriver-binary ... error
    ERROR: Command errored out with exit status 1:
     command: /vvv/.venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py'"'"'; __file__='"'"'/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-record-xojoopgr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/trfiladelfo/Projetos/Pessoal/catapreco/.venv/include/site/python3.8/chromedriver-binary
         cwd: /private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/
    Complete output (79 lines):
    running install
    running build
    running build_py
    
    Downloading Chromedriver...
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py", line 44, in run
        response = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>
    
    During handling of the above exception, another exception occurred:
      File "/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py", line 48, in run
        raise RuntimeError('Failed to download chromedriver archive: {}'.format(url))
    RuntimeError: Failed to download chromedriver archive: https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_mac64.zip
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/trfiladelfo/Projetos/Pessoal/catapreco/.venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py'"'"'; __file__='"'"'/private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-install-4o_wm5dr/chromedriver-binary_e318230147334d138dfa7ced57516155/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/30/r4y3q7y15cddf07h0c54v29m0000gn/T/pip-record-xojoopgr/install-record.txt --single-version-externally-managed --compile --install-headers

My profile:
Python: 3.8.2
Operational System: MacOsx Big Sur - 11.3.1 

Obs.: I'll send a pull request solving this 
Thanks

**Comment by danielkaiser** [comment]
Hi, please see my comment on your PR.
Sorry again for the long delay and maybe check [for example this thread](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify) on certificate verification issues with Python on MacOS.
